server:
  port: 8761

spring:
  application:
    name: discovery-server

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # We set this to false because this IS the server, it shouldn't register itself
    fetch-registry: false