server:
  port: 8081

spring:
  cloud:
    discovery:
      enabled: true       #make true for eureka

  application:
    name: product-service
  mongodb:
    uri: ${MONGODB_URI:mongodb://localhost:27017/bidcraft_products}
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  instance:
    preferIpAddress: true
  client:
    enabled: true       #make true for eureka
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
