server:
  port: 8081

spring:
  cloud:
    discovery:
      enabled: false       #make true for eureka

  application:
    name: product-service
  mongodb:
    uri: ${MONGODB_URI} # Your existing config
  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    enabled: false       #make true for eureka
    service-url:
      defaultZone: http://localhost:8761/eureka/